(function() {var implementors = {
"arti_client":[["impl <a class=\"trait\" href=\"arti_client/trait.HasKind.html\" title=\"trait arti_client::HasKind\">HasKind</a> for <a class=\"struct\" href=\"arti_client/struct.Error.html\" title=\"struct arti_client::Error\">Error</a>"]],
"tor_cell":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_cell/enum.Error.html\" title=\"enum tor_cell::Error\">Error</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"struct\" href=\"tor_cell/relaycell/msg/struct.EndReason.html\" title=\"struct tor_cell::relaycell::msg::EndReason\">EndReason</a>"]],
"tor_chanmgr":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_chanmgr/enum.Error.html\" title=\"enum tor_chanmgr::Error\">Error</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_chanmgr/transport/enum.ProxyError.html\" title=\"enum tor_chanmgr::transport::ProxyError\">ProxyError</a>"]],
"tor_circmgr":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_circmgr/enum.Error.html\" title=\"enum tor_circmgr::Error\">Error</a>"]],
"tor_config":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_config/enum.ConfigBuildError.html\" title=\"enum tor_config::ConfigBuildError\">ConfigBuildError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_config/enum.ReconfigureError.html\" title=\"enum tor_config::ReconfigureError\">ReconfigureError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_config/enum.CfgPathError.html\" title=\"enum tor_config::CfgPathError\">CfgPathError</a>"]],
"tor_dirclient":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"struct\" href=\"tor_dirclient/struct.RequestFailedError.html\" title=\"struct tor_dirclient::RequestFailedError\">RequestFailedError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_dirclient/enum.Error.html\" title=\"enum tor_dirclient::Error\">Error</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_dirclient/enum.RequestError.html\" title=\"enum tor_dirclient::RequestError\">RequestError</a>"]],
"tor_dirmgr":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_dirmgr/enum.Error.html\" title=\"enum tor_dirmgr::Error\">Error</a>"]],
"tor_error":[],
"tor_guardmgr":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_guardmgr/enum.GuardMgrConfigError.html\" title=\"enum tor_guardmgr::GuardMgrConfigError\">GuardMgrConfigError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_guardmgr/enum.PickGuardError.html\" title=\"enum tor_guardmgr::PickGuardError\">PickGuardError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_guardmgr/enum.GuardMgrError.html\" title=\"enum tor_guardmgr::GuardMgrError\">GuardMgrError</a>"]],
"tor_hsclient":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_hsclient/enum.ConnError.html\" title=\"enum tor_hsclient::ConnError\">ConnError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_hsclient/enum.DescriptorErrorDetail.html\" title=\"enum tor_hsclient::DescriptorErrorDetail\">DescriptorErrorDetail</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"struct\" href=\"tor_hsclient/struct.DescriptorError.html\" title=\"struct tor_hsclient::DescriptorError\">DescriptorError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_hsclient/enum.StartupError.html\" title=\"enum tor_hsclient::StartupError\">StartupError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_hsclient/enum.FailedAttemptError.html\" title=\"enum tor_hsclient::FailedAttemptError\">FailedAttemptError</a>"]],
"tor_hscrypto":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_hscrypto/pk/enum.HsIdParseError.html\" title=\"enum tor_hscrypto::pk::HsIdParseError\">HsIdParseError</a>"]],
"tor_netdir":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_netdir/enum.OnionDirLookupError.html\" title=\"enum tor_netdir::OnionDirLookupError\">OnionDirLookupError</a>"],["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_netdir/enum.Error.html\" title=\"enum tor_netdir::Error\">Error</a>"]],
"tor_netdoc":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_netdoc/doc/hsdesc/enum.HsDescError.html\" title=\"enum tor_netdoc::doc::hsdesc::HsDescError\">HsDescError</a>"]],
"tor_persist":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"struct\" href=\"tor_persist/struct.Error.html\" title=\"struct tor_persist::Error\">Error</a>"]],
"tor_proto":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_proto/enum.Error.html\" title=\"enum tor_proto::Error\">Error</a>"]],
"tor_socksproto":[["impl <a class=\"trait\" href=\"tor_error/trait.HasKind.html\" title=\"trait tor_error::HasKind\">HasKind</a> for <a class=\"enum\" href=\"tor_socksproto/enum.Error.html\" title=\"enum tor_socksproto::Error\">Error</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()